version: '3.3'
services:
  viroblast:
    image: sc-registry.fredhutch.org/viroblast:latest
    volumes:
      - viroblast_persistent:/viroblast_data
    networks:
      - sc-swarm-net
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.viroblast.rule=Host(`viroblast.fredhutch.org`)"
        - "traefik.http.routers.viroblast-secured.rule=Host(`viroblast.fredhutch.org`)"
        - "traefik.http.routers.viroblast.entrypoints=web,web-secured"
        - "traefik.http.services.viroblast.loadbalancer.server.port=80" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.viroblast.tls=true"

networks:
  sc-swarm-net:
    external: true

volumes:
  viroblast_persistent:
    driver: local
    driver_opts:
      type: nfs
      device: "${PERSISTENT_VOLUME_PATH}"
      o: addr=${NFS_SERVER},rw
